# Generated by Django 5.0.6 on 2024-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/assets/avatar.svg', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
